# raku-search app.yaml

env: standard

service: default
runtime: python311

instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_instances: 1


handlers:
- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /favicon.ico
  static_files: application/static/favicon.ico
  upload: application/static/favicon.ico

- url: /static
  static_dir: application/static
  expiration: "7d"
  http_headers:
    Vary: Accept-Encoding

- url: /.*
  secure: always
  script: auto
  
